package main

var books = map[string]book{
	"American Government": {
		BookName:           "American Government",
		FileName:           "us-government-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "16.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Anatomy and Physiology": {
		BookName:           "Anatomy and Physiology",
		FileName:           "anatomy-physiology-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Algonquin College MAT0032": {
		BookName:           "Algonquin College MAT0032",
		FileName:           "algonquin-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Applied Finite Mathematics": {
		BookName:           "Applied Finite Mathematics",
		FileName:           "applied-finite-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Principles of Macroeconomics for AP Courses 2e": {
		BookName:           "Principles of Macroeconomics for AP Courses 2e",
		FileName:           "principles-macro2e-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"College Physics for AP Courses": {
		BookName:           "College Physics for AP Courses",
		FileName:           "college-physics-ap-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Astronomy": {
		BookName:           "Astronomy",
		FileName:           "astronomy-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Biology": {
		BookName:           "Biology",
		FileName:           "biology-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Biology for AP Courses": {
		BookName:           "Biology for AP Courses",
		FileName:           "apbiology-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Biology 2e": {
		BookName:           "Biology 2e",
		FileName:           "biology2e-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Business Ethics": {
		BookName:           "Business Ethics",
		FileName:           "business-ethics-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Calculus Volume 1": {
		BookName:           "Calculus Volume 1",
		FileName:           "calculus-vol1-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Chemistry": {
		BookName:           "Chemistry",
		FileName:           "chemistry-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Collaborative Statistics Modified by T Short": {
		BookName:           "Collaborative Statistics Modified by T Short",
		FileName:           "collaborative-statistics-tshort-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Labs For Collaborative Statistics Teegarden": {
		BookName:           "Labs For Collaborative Statistics Teegarden",
		FileName:           "collaborative-statistics-teegarden-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"College Algebra": {
		BookName:           "College Algebra",
		FileName:           "college-algebra-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"College Physics": {
		BookName:           "College Physics",
		FileName:           "college-physics-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Concepts of Biology": {
		BookName:           "Concepts of Biology",
		FileName:           "concepts-biology-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Elementary Algebra": {
		BookName:           "Elementary Algebra",
		FileName:           "elementary-algebra-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"English Home Language Grade 5": {
		BookName:           "English Home Language Grade 5",
		FileName:           "english-home-language-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Human Anatomy": {
		BookName:           "Human Anatomy",
		FileName:           "human-anatomy-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"KSU TM College Physics I": {
		BookName:           "KSU TM College Physics I",
		FileName:           "ksu-tm-college-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Microbiology": {
		BookName:           "Microbiology",
		FileName:           "microbiology-raw.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Intermediate Algebra": {
		BookName:           "Intermediate Algebra",
		FileName:           "intro-algebra-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Introductory Statistics": {
		BookName:           "Introductory Statistics",
		FileName:           "intro-stats-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Introduction to Business": {
		BookName:           "Introduction to Business",
		FileName:           "intro-business-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Introductory Business Statistics": {
		BookName:           "Introductory Business Statistics",
		FileName:           "intro-business-stats-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Prealgebra": {
		BookName:           "Prealgebra",
		FileName:           "prealgebra-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Principles of Economics 2e": {
		BookName:           "Principles of Economics 2e",
		FileName:           "principles-economics2e-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Project Management": {
		BookName:           "Project Management",
		FileName:           "project-managment-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Psychology": {
		BookName:           "Psychology",
		FileName:           "psychology-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Fizyka dla szkol wyzszych Tom 1": {
		BookName:           "Fizyka dla szkol wyzszych Tom 1",
		FileName:           "katalyst-physics-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Rationality": {
		BookName:           "Rationality",
		FileName:           "rationality-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Introduction to Sociology 2e": {
		BookName:           "Introduction to Sociology 2e",
		FileName:           "intro-sociology2e-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"Understanding Basic Music Theory": {
		BookName:           "Understanding Basic Music Theory",
		FileName:           "basic-music-theory-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "21.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"University Physics Volume 1": {
		BookName:           "University Physics Volume 1",
		FileName:           "u-physics-baked.xhtml",
		Baked:              true,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
	"US History": {
		BookName:           "US History",
		FileName:           "us-history-raw.xhtml",
		Baked:              false,
		ContentFetchedAt:   "15.11.2018",
		ContentFetchedFrom: "katalyst01.cnx.org",
	},
}
